pkg load symbolic
syms x x1 x2 x3 x4 x5 f(x) h
p = f(x1)*((x-x2)*(x-x3)*(x-x4)*(x-x5))...
         /((x1-x2)*(x1-x3)*(x1-x4)*(x1-x5)) ...
  + f(x2)*((x-x1)*(x-x3)*(x-x4)*(x-x5))...
         /((x2-x1)*(x2-x3)*(x2-x4)*(x2-x5)) ...
  + f(x3)*((x-x1)*(x-x2)*(x-x4)*(x-x5))...
         /((x3-x1)*(x3-x2)*(x3-x4)*(x3-x5)) ...
  + f(x4)*((x-x1)*(x-x2)*(x-x3)*(x-x5))...
         /((x4-x1)*(x4-x2)*(x4-x3)*(x4-x5)) ...
  + f(x5)*((x-x1)*(x-x2)*(x-x3)*(x-x4))...
         /((x5-x1)*(x5-x2)*(x5-x3)*(x5-x4));
         
dp = diff(p,x);

#4pts. para traz
dfa = simplify(subs(dp,{x1,x2,x3,x4,x5},...
                       {x-4*h,x-3*h,x-2*h,x-h,x}))
latex(dfa)

#3pts. para traz e 1pt para frente
dfb = simplify(subs(dp,{x1,x2,x3,x4,x5},...
                       {x-3*h,x-2*h,x-h,x,x+h}))
latex(dfb)

#2pts. para traz e 2pts para frente
dfc = simplify(subs(dp,{x1,x2,x3,x4,x5},...
                       {x-2*h,x-h,x,x+h,x+2*h}))
latex(dfc)

#1pts. para traz e 3pts para frente
dfd = simplify(subs(dp,{x1,x2,x3,x4,x5},...
                       {x-h,x,x+h,x+2*h,x+3*h}))
latex(dfd)

#4pts para frente
dfe = simplify(subs(dp,{x1,x2,x3,x4,x5},...
                       {x,x+h,x+2*h,x+3*h,x+4*h}))
latex(dfe)
