all: main.py
	python3 main.py

Index: mainIndex.py
	python3 mainIndex.py

Politica: mainPolitica.py
	python3 mainPolitica.py

AlgoritmosProgramacaoI: mainAlgoritmosProgramacaoI.py
	python3 mainAlgoritmosProgramacaoI.py

CalculoI: mainCalculoI.py
	python3 mainCalculoI.py

EaD: mainEaD.py
	python3 mainEaD.py

EDO: mainEDO.py
	python3 mainEDO.py

GeometriaAnalitica: mainGeometriaAnalitica.py
	python3 mainGeometriaAnalitica.py

MatematicaNumerica: mainMatematicaNumerica.py
	python3 mainMatematicaNumerica.py

MatematicaNumericaI: mainMatematicaNumericaI.py
	python3 mainMatematicaNumericaI.py

MatematicaNumericaII: mainMatematicaNumericaII.py
	python3 mainMatematicaNumericaII.py

MatematicaNumericaAvancada: mainMatematicaNumericaAvancada.py
	python3 mainMatematicaNumericaAvancada.py

MatematicaNumericaParalela: mainMatematicaNumericaParalela.py
	python3 mainMatematicaNumericaParalela.py

MetodoElementosFinitos: mainMetodoElementosFinitos.py
	python3 mainMetodoElementosFinitos.py

PreCalculo: mainPreCalculo.py
	python3 mainPreCalculo.py

Teste: mainTeste.py
	python3 mainTeste.py

Vetores: mainVetores.py
	python3 mainVetores.py

MiniCalcPy: mainMiniCalcPy.py
	python3 mainMiniCalcPy.py

MiniPython: mainMiniPython.py
	python3 mainMiniPython.py

.PHONY: clean

clean:
	rm -rvf .src .docs
